// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineStore.MultiTenant.Api.Contexts;

#nullable disable

namespace OnlineStore.MultiTenant.Api.Migrations
{
    [DbContext(typeof(OnlineStoreContext))]
    [Migration("20240319231049_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OnlineStore.MultiTenant.Api.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("96cc899a-519e-4eaa-ac95-2eb6f8b2949c"),
                            CreationDate = new DateTime(2024, 3, 20, 0, 10, 49, 722, DateTimeKind.Local).AddTicks(4936),
                            CustomerId = new Guid("019fc834-c3d7-4a57-ba91-97f7b63363c5")
                        },
                        new
                        {
                            Id = new Guid("01edb615-6d07-4a24-9016-12412271dd04"),
                            CreationDate = new DateTime(2024, 3, 20, 0, 10, 49, 722, DateTimeKind.Local).AddTicks(4984),
                            CustomerId = new Guid("c52ae0d7-e8ab-4ff8-a0e7-6634895001e1")
                        });
                });

            modelBuilder.Entity("OnlineStore.MultiTenant.Api.Models.OrderItem", b =>
                {
                    b.Property<Guid>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightInKg")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            OrderItemId = new Guid("3adad5f7-fdc6-402b-8f5e-d417420aebb4"),
                            Price = 120.0m,
                            ProductId = new Guid("a7be5fd1-0bef-4d62-886d-29dfab419d83"),
                            Quantity = 1,
                            WeightInKg = 3.5m
                        },
                        new
                        {
                            OrderItemId = new Guid("62090a64-1b6b-4502-8fa2-25a822ff23cb"),
                            Price = 45.0m,
                            ProductId = new Guid("0c5ecb09-5da9-443a-b155-be0465c8202a"),
                            Quantity = 2,
                            WeightInKg = 0.5m
                        },
                        new
                        {
                            OrderItemId = new Guid("29253941-e6c1-41ce-8d96-cd487f7f174c"),
                            Price = 80.0m,
                            ProductId = new Guid("396be858-4b5b-4ccd-9bbd-8f7328b9390c"),
                            Quantity = 1,
                            WeightInKg = 1.0m
                        });
                });

            modelBuilder.Entity("OnlineStore.MultiTenant.Api.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("adec8f41-95c3-4edf-af79-ebe2db93157e"),
                            Description = "A vintage typewriter for the nostalgic writer.",
                            Name = "Vintage Typewriter",
                            Price = 120.0m
                        },
                        new
                        {
                            ProductId = new Guid("f1294e07-26be-44e1-8198-80713150e390"),
                            Description = "A handcrafted leather notebook for your thoughts.",
                            Name = "Leather Notebook",
                            Price = 45.0m
                        },
                        new
                        {
                            ProductId = new Guid("5d302965-7a19-454a-97cc-6671faed4891"),
                            Description = "A stylish wooden desk lamp for your workspace.",
                            Name = "Wooden Desk Lamp",
                            Price = 80.0m
                        });
                });

            modelBuilder.Entity("OnlineStore.MultiTenant.Api.Models.OrderItem", b =>
                {
                    b.HasOne("OnlineStore.MultiTenant.Api.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("OnlineStore.MultiTenant.Api.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
